import fs from "node:fs";

function autogenSchema() {
    console.log("Autogenerating schema ...");

    try {
    fs.writeFileSync('schema.sql', `
DROP TABLE IF EXISTS waitlist;
DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS specialties;
        
${autogenRegionSQL()}
${autogenSpecialtySQL()}
${autogenWaitlistSQL()}
`); } catch (error) {
    console.error("Error writing SQL to file: ", error )
    }

    console.log('Schema autogenerated and saved to file ./schema.sql')
}


function autogenRegionSQL() {
    let regionData = [];

    console.log("Reading region data from file data/regions.json");
    try {
        const regions = fs.readFileSync('./src/data/autogen/regions.json', 'utf-8');
        regionData = JSON.parse(regions);
    } catch (error) {
        console.error("Error reading src/regions.json: ", error)
    }

    return `
CREATE TABLE IF NOT EXISTS regions (code TEXT PRIMARY KEY, name TEXT);
${regionData.map((data) => {
    return `INSERT INTO regions (code, name) VALUES ("${data.code}", "${data.name}");`
}).join("\n")}
    `
}

function autogenSpecialtySQL() {
    let specialtyData = [];

    console.log("Reading region data from file data/specialties.json");
    try {
        const specialties = fs.readFileSync('./src/data/specialties.json', 'utf-8');
        specialtyData = JSON.parse(specialties);
    } catch (error) {
        console.error("Error reading src/specialties.json: ", error)
    }

    return `
CREATE TABLE IF NOT EXISTS specialties (id TEXT PRIMARY KEY, name TEXT);
${specialtyData.map((data) => {
    return `INSERT INTO specialties (id, name) VALUES ("${data.id}", "${data.name}");`
}).join("\n")}
    `
}

function autogenWaitlistSQL() {
    let waitlistData = [];

    console.log("Reading region data from file data/autogen/waitlist.json");
    try {
        const waitlist = fs.readFileSync('./src/data/autogen/waitlist.json', 'utf-8');
        waitlistData = JSON.parse(waitlist);
    } catch (error) {
        console.error("Error reading waitlist.json: ", error)
    }

    return `
CREATE TABLE IF NOT EXISTS waitlist (id INTEGER PRIMARY KEY, region TEXT, year TEXT, period TEXT, delay TEXT, total INTEGER, other INTEGER, general INTEGER, orthopedic INTEGER, plastic INTEGER, vascular INTEGER, neuro INTEGER, entf INTEGER, obgyn INTEGER, opthamology INTEGER, urology INTEGER, FOREIGN KEY (region) REFERENCES regions(code));
${waitlistData.map((data, index) => {
    return `INSERT INTO waitlist (id, region, year, period, delay, total, other, general, orthopedic, plastic, vascular, neuro, entf, obgyn, opthamology, urology) VALUES (${index}, "${data.region}", "${data.year}", "${data.period}", "${data.delay}", ${data.total}, ${data.other}, ${data.general}, ${data.orthopedic}, ${data.plastic}, ${data.vascular}, ${data.neuro}, ${data.entf}, ${data.obgyn}, ${data.opthamology}, ${data.urology});`;
}).join("\n")}
    `
}


autogenSchema();